imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: "%use_assetic_controller%"

#swiftmailer:
#    delivery_address: me@example.com

h4cc_alice_fixtures:
    locale: en_US
    seed: 42
    do_flush: true

    schema_tool: null
    doctrine: orm

qa_system_core:
  tasks:
    echo:
      name: echo
      command: "echo {{text}}"
      parameters:
        text:
          name: "Text to print"
          code: text
          type: script
          script: "php /private/var/www/php-deployment-tool/app/data/scripts/github-branches.php"
